### ISSUE TITLE
well_data.py fails when predicting guassian1d on first time step

### ISSUE THREAD

**Issue by setseed42** [mathDR/abocpd#1]
When running `bocpd_deriv` at t==0, `gaussian1D.predict` tries to access a multidimensional matrix `dpost_params` which was only been initialised as an empty array.

```bash
Traceback (most recent call last):
  File "well_data.py", line 57, in <module>
    bocpd_dwrap1D(theta, X, model_f, hazard_f, conversion)
  File "/Users/erik/devs/abocpd/learn_bocpd.py", line 34, in bocpd_dwrap1D
    nlml, dnlml_h, dnlml_m = bocpd_deriv(theta_h, theta_m, X, hazard_f, model_f)
  File "/Users/erik/devs/abocpd/bocpd_deriv.py", line 41, in bocpd_deriv
    model_f.predict(X[t,:], needDerivatives=True)
  File "/Users/erik/devs/abocpd/UPM/gaussian1D.py", line 89, in predict
    dmu_dtheta    = np.transpose(self.dpost_params[0,:,:], axes=[2,1,0]) # N x 4
IndexError: too many indices for array
```

Tested with python==2.7, numpy==1.16.5, scipy==1.2.1

Is it possible to get an specification of the environment in which this has successfully run?

**Comment by mathDR** [comment]
Hey @setseed42 I was looking this over, and IMHO this repo needs to be completely refactored (I pushed some changes to respect python 3 and to get some of the tests to run) and I do not have anytime to spare on this.

I successfully ran the Hazards tests and ran the gaussiandemo.  Could you do that?
